name: Integration Tests

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - "*"
  schedule:
    - cron: '0 0 * * *'

jobs:
  php-laravel-integration-tests:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    env:
      COMPOSER_NO_INTERACTION: 1
    strategy:
      fail-fast: false
      matrix:
        php: [8.4, 8.3, 8.2, 8.1]
        laravel: [11.*, 10.*, 9.*, 8.*]
        exclude:
          - laravel: 11.*
            php: 8.1
          - laravel: 11.*
            php: 8.2
          - laravel: 11.*
            php: 8.3
          - laravel: 11.*
            php: 8.4
          - laravel: 9.*
            php: 8.4
          - laravel: 8.*
            php: 7.4
    name: P${{ matrix.php }} - Laravel${{ matrix.laravel }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          path: src

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          coverage: none
          tools: composer:v2

      - name: Install dependencies
        run: |
          composer create-project --prefer-dist laravel/laravel:${{ matrix.laravel }} --stability=dev --no-progress sample
          cd sample
          composer config minimum-stability dev
          composer update --prefer-stable --prefer-dist --no-progress

      - name: Add package from source
        run: |
          cd sample
          sed -e 's|"type": "project",|&\n"repositories": [ { "type": "path", "url": "../src" } ],|' -i composer.json
          composer require "prettus/l5-repository:*"

      - name: Run integration tests
        run: |
          cd sample
          php artisan test
